#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import process from 'process'
import { fileURLToPath } from 'url'

const repoRoot = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const envFile = path.join(repoRoot, '.env.local')
const outputFile = path.join(repoRoot, 'src', 'secrets.generated.ts')

const secretNames = [
  'ALIYUN_APP_ID',
  'ALIYUN_APP_SECRET',
  'APPLE_ID',
  'APPLE_PASSWORD',
  'APPLE_TEAM_ID'
]

function parseArgs(argv) {
  return {
    mode: argv.find((arg) => arg.startsWith('--mode='))?.split('=')[1] || 'local',
    strict: argv.includes('--strict')
  }
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {}
  const output = {}
  const text = fs.readFileSync(filePath, 'utf8')
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/)
    if (!match) continue
    const key = match[1]
    let value = match[2].trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }
    output[key] = value.replace(/\\n/g, '\n')
  }
  return output
}

function readExistingValues(filePath) {
  // Values already present in src/secrets.generated.ts (for example hand-filled OpenAPI credentials).
  if (!fs.existsSync(filePath)) return {}
  const output = {}
  const text = fs.readFileSync(filePath, 'utf8')
  const re = /^export const ([A-Z0-9_]+) = ("(?:[^"\\]|\\.)*")$/gm
  let match
  while ((match = re.exec(text))) {
    try {
      output[match[1]] = JSON.parse(match[2])
    } catch {}
  }
  return output
}

function readRequiredNames() {
  const raw = process.env.REQUIRED_RELEASE_SECRETS || ''
  return raw
    .split(',')
    .map((name) => name.trim())
    .filter(Boolean)
}

function main() {
  const args = parseArgs(process.argv.slice(2))
  const localEnv = args.mode === 'ci' ? {} : parseEnvFile(envFile)
  const existing = args.mode === 'ci' ? {} : readExistingValues(outputFile)
  const values = {}
  const kept = []

  for (const name of secretNames) {
    let value = process.env[name] ?? localEnv[name] ?? ''
    // Never clobber a value that was already generated/filled in when nothing new is configured.
    if (!value && existing[name]) {
      value = existing[name]
      kept.push(name)
    }
    values[name] = value
  }

  const required = args.strict ? readRequiredNames() : []
  const missing = required.filter((name) => !values[name])
  if (missing.length) {
    console.error(`Missing required release secrets: ${missing.join(', ')}`)
    process.exit(1)
  }

  const lines = [
    '// This file is generated by scripts/generate-secrets.mjs.',
    '// Do not edit manually. Do not commit real secret values.',
    ''
  ]

  for (const name of secretNames) {
    lines.push(`export const ${name} = ${JSON.stringify(values[name])}`)
  }
  lines.push('')

  fs.mkdirSync(path.dirname(outputFile), { recursive: true })
  fs.writeFileSync(outputFile, lines.join('\n'), 'utf8')

  const filled = secretNames.filter((name) => values[name]).length
  console.log(`Generated src/secrets.generated.ts (${filled}/${secretNames.length} values set, mode=${args.mode}${kept.length ? `, kept existing: ${kept.join(', ')}` : ''})`)
  if (!values.ALIYUN_APP_ID || !values.ALIYUN_APP_SECRET) {
    console.warn('ALIYUN_APP_ID / ALIYUN_APP_SECRET are empty: put them in .env.local or enter your own OpenAPI credentials in 设置 → 账户设置 → OpenAPI 授权.')
  }
}

main()
