// Copy of the shape generated by scripts/generate-secrets.mjs (src/secrets.generated.ts).
export const ALIYUN_APP_ID = ''
export const ALIYUN_APP_SECRET = ''
export const APPLE_ID = ''
export const APPLE_PASSWORD = ''
export const APPLE_TEAM_ID = ''
